### ISSUE TITLE
Our results are better with tensorflow movenet

### ISSUE THREAD

**Issue by jigratz** [lee-man/movenet-pytorch#4]
Hello- Nice work on this. We've run some initial tests and are finding that the results from the original tensorflow movenet (https://colab.research.google.com/github/tensorflow/hub/blob/master/examples/colab/movenet.ipynb) are different than the results we're seeing with your implementation.

Original movenet:
![movenet-colab](https://user-images.githubusercontent.com/81345856/144692758-7fff1dd0-3392-43dc-a8ef-6592836e1d66.PNG)

This implementation:
![movenet-pytorch](https://user-images.githubusercontent.com/81345856/144692773-2f7b6595-8e7c-4ffd-904d-095a181f7216.PNG)

We're running both with the "thunder" model. Is there something we're doing incorrectly or a modification we need to make?

Best Regards.

**Comment by lee-man** [comment]
It may due to the subtle difference in implementation of `up-sampling` in https://github.com/lee-man/movenet-pytorch/blob/main/movenet/models/feature_pyramid_network.py
Or the difference in post-processing. I have no clear idea.

**Comment by lee-man** [comment]
@jigratz Another possible reason is the difference in the version you used for the demo. The weights I extracted are from MoveNet Version 3.
