### ISSUE TITLE
pre-process is different from your movenet repo: normalize image

### ISSUE THREAD

**Issue by juno-ml** [lee-man/movenet-pytorch#6]
First of all thanks for sharing good code.
I came across a question while looking at your code. When training(in your movenet repo), the input images are normalized by means & stds, but here, the values ​​between 0 and 255 are just used. Is there another reason for not normalizing images as training?

**Comment by lee-man** [comment]
Hi,

In order to keep the pre-processing in the TFLite models, the normalization steps are merged into the model definition. You can check: https://github.com/lee-man/movenet-pytorch/blob/main/movenet/models/movenet.py#L90

**Comment by juno-ml** [comment]
Ah..I got it! Thanks :+1:
