### ISSUE TITLE
Sota result or just for fun？

### ISSUE THREAD

**Issue by 2050airobert** [lee-man/movenet-pytorch#7]
hi，
1 这个结果跟原始tensorflow的movenet模型效果一致还是有所提升？
2 该结果精度有跟目前主流或者sota对比过吗？
3 为了改善视频的有效性范围，有木有尝试加入boneloss 等其他loss或者一些特殊的处理？

BR

**Comment by lee-man** [comment]
1. 效果一致，因为参数都是tflite上提取出来的。
2. 没有，这个repo只考虑浮现movenet inference的效果。
3. 没有。
感谢！
